
INSERT INTO PERSON VALUES ('IwlZrMYl', 'IwlZrMYl');


INSERT INTO PERSON VALUES ('OoxuLbZw', 'OoxuLbZw');


INSERT INTO PERSON VALUES ('QplYUoXT', 'QplYUoXT');


INSERT INTO PERSON VALUES ('FxClDJpm', 'FxClDJpm');


INSERT INTO PERSON VALUES ('zlvyVFhp', 'zlvyVFhp');


INSERT INTO PERSON VALUES ('sKpArCJO', 'sKpArCJO');


INSERT INTO PERSON VALUES ('EqThvpIa', 'EqThvpIa');


INSERT INTO PERSON VALUES ('WTGooNNo', 'WTGooNNo');


INSERT INTO PERSON VALUES ('MBkDcQct', 'MBkDcQct');


INSERT INTO PERSON VALUES ('PSYDlBAV', 'PSYDlBAV');


INSERT INTO PERSON VALUES ('PsaoGcfA', 'PsaoGcfA');


INSERT INTO PERSON VALUES ('TtXmfTuI', 'TtXmfTuI');


INSERT INTO PERSON VALUES ('mbpNDSQd', 'mbpNDSQd');


INSERT INTO PERSON VALUES ('BIheaZWj', 'BIheaZWj');


INSERT INTO PERSON VALUES ('OoOpJoAs', 'OoOpJoAs');


INSERT INTO PERSON VALUES ('DTjIrqme', 'DTjIrqme');


INSERT INTO PERSON VALUES ('arHLPHln', 'arHLPHln');


INSERT INTO PERSON VALUES ('vqypCMxJ', 'vqypCMxJ');


INSERT INTO PERSON VALUES ('zExYkTNa', 'zExYkTNa');


INSERT INTO PERSON VALUES ('IRkqYJPO', 'IRkqYJPO');


INSERT INTO PERSON VALUES ('VLQxglhe', 'VLQxglhe');


INSERT INTO PERSON VALUES ('EhXSPePR', 'EhXSPePR');


INSERT INTO PERSON VALUES ('cGKofSNQ', 'cGKofSNQ');


INSERT INTO PERSON VALUES ('vzSdOUdB', 'vzSdOUdB');


INSERT INTO PERSON VALUES ('jEXrdyCX', 'jEXrdyCX');


INSERT INTO PERSON VALUES ('gGaYRiFo', 'gGaYRiFo');


INSERT INTO PERSON VALUES ('lBRureMT', 'lBRureMT');


INSERT INTO PERSON VALUES ('RDBeUwQi', 'RDBeUwQi');


INSERT INTO PERSON VALUES ('GXnhZnMZ', 'GXnhZnMZ');


INSERT INTO PERSON VALUES ('QeszNSut', 'QeszNSut');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'lBRureMT');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('IwlZrMYl', 'QeszNSut');


INSERT INTO FRIEND VALUES ('OoxuLbZw', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('OoxuLbZw', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('OoxuLbZw', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('OoxuLbZw', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('OoxuLbZw', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('OoxuLbZw', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('OoxuLbZw', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('OoxuLbZw', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('OoxuLbZw', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('OoxuLbZw', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('OoxuLbZw', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('OoxuLbZw', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('QplYUoXT', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('QplYUoXT', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('QplYUoXT', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('QplYUoXT', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('QplYUoXT', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('QplYUoXT', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('QplYUoXT', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('QplYUoXT', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('QplYUoXT', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('QplYUoXT', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('QplYUoXT', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('QplYUoXT', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('QplYUoXT', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'arHLPHln');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'lBRureMT');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('FxClDJpm', 'QeszNSut');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'arHLPHln');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('zlvyVFhp', 'QeszNSut');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'lBRureMT');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('sKpArCJO', 'QeszNSut');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'arHLPHln');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'lBRureMT');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('EqThvpIa', 'QeszNSut');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'lBRureMT');


INSERT INTO FRIEND VALUES ('WTGooNNo', 'QeszNSut');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'arHLPHln');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('MBkDcQct', 'lBRureMT');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'arHLPHln');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'lBRureMT');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('PSYDlBAV', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'arHLPHln');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'lBRureMT');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('PsaoGcfA', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'arHLPHln');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'lBRureMT');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('TtXmfTuI', 'QeszNSut');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'arHLPHln');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'lBRureMT');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('mbpNDSQd', 'QeszNSut');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('BIheaZWj', 'QeszNSut');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'arHLPHln');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'lBRureMT');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('OoOpJoAs', 'QeszNSut');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'lBRureMT');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('DTjIrqme', 'QeszNSut');


INSERT INTO FRIEND VALUES ('arHLPHln', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('arHLPHln', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('arHLPHln', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('arHLPHln', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('arHLPHln', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('arHLPHln', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('arHLPHln', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('arHLPHln', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('arHLPHln', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('arHLPHln', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('arHLPHln', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('arHLPHln', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('arHLPHln', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('arHLPHln', 'lBRureMT');


INSERT INTO FRIEND VALUES ('arHLPHln', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'arHLPHln');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('vqypCMxJ', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('zExYkTNa', 'QeszNSut');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('IRkqYJPO', 'QeszNSut');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'arHLPHln');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'lBRureMT');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('VLQxglhe', 'QeszNSut');


INSERT INTO FRIEND VALUES ('EhXSPePR', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('EhXSPePR', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('EhXSPePR', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('EhXSPePR', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('EhXSPePR', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('EhXSPePR', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('EhXSPePR', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('EhXSPePR', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('EhXSPePR', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('EhXSPePR', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('EhXSPePR', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('EhXSPePR', 'lBRureMT');


INSERT INTO FRIEND VALUES ('EhXSPePR', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('EhXSPePR', 'QeszNSut');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'arHLPHln');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'lBRureMT');


INSERT INTO FRIEND VALUES ('cGKofSNQ', 'QeszNSut');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'lBRureMT');


INSERT INTO FRIEND VALUES ('vzSdOUdB', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'arHLPHln');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('jEXrdyCX', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'PSYDlBAV');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'mbpNDSQd');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'GXnhZnMZ');


INSERT INTO FRIEND VALUES ('gGaYRiFo', 'QeszNSut');


INSERT INTO FRIEND VALUES ('lBRureMT', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('lBRureMT', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('lBRureMT', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('lBRureMT', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('lBRureMT', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('lBRureMT', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('lBRureMT', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('lBRureMT', 'arHLPHln');


INSERT INTO FRIEND VALUES ('lBRureMT', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('lBRureMT', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('lBRureMT', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('lBRureMT', 'EhXSPePR');


INSERT INTO FRIEND VALUES ('lBRureMT', 'cGKofSNQ');


INSERT INTO FRIEND VALUES ('lBRureMT', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('lBRureMT', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'zExYkTNa');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'IRkqYJPO');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'vzSdOUdB');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'lBRureMT');


INSERT INTO FRIEND VALUES ('RDBeUwQi', 'QeszNSut');


INSERT INTO FRIEND VALUES ('GXnhZnMZ', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('GXnhZnMZ', 'OoxuLbZw');


INSERT INTO FRIEND VALUES ('GXnhZnMZ', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('GXnhZnMZ', 'FxClDJpm');


INSERT INTO FRIEND VALUES ('GXnhZnMZ', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('GXnhZnMZ', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('GXnhZnMZ', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('GXnhZnMZ', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('GXnhZnMZ', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('GXnhZnMZ', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('GXnhZnMZ', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('GXnhZnMZ', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('GXnhZnMZ', 'RDBeUwQi');


INSERT INTO FRIEND VALUES ('GXnhZnMZ', 'QeszNSut');


INSERT INTO FRIEND VALUES ('QeszNSut', 'IwlZrMYl');


INSERT INTO FRIEND VALUES ('QeszNSut', 'QplYUoXT');


INSERT INTO FRIEND VALUES ('QeszNSut', 'zlvyVFhp');


INSERT INTO FRIEND VALUES ('QeszNSut', 'sKpArCJO');


INSERT INTO FRIEND VALUES ('QeszNSut', 'EqThvpIa');


INSERT INTO FRIEND VALUES ('QeszNSut', 'WTGooNNo');


INSERT INTO FRIEND VALUES ('QeszNSut', 'MBkDcQct');


INSERT INTO FRIEND VALUES ('QeszNSut', 'PsaoGcfA');


INSERT INTO FRIEND VALUES ('QeszNSut', 'TtXmfTuI');


INSERT INTO FRIEND VALUES ('QeszNSut', 'BIheaZWj');


INSERT INTO FRIEND VALUES ('QeszNSut', 'OoOpJoAs');


INSERT INTO FRIEND VALUES ('QeszNSut', 'DTjIrqme');


INSERT INTO FRIEND VALUES ('QeszNSut', 'arHLPHln');


INSERT INTO FRIEND VALUES ('QeszNSut', 'vqypCMxJ');


INSERT INTO FRIEND VALUES ('QeszNSut', 'VLQxglhe');


INSERT INTO FRIEND VALUES ('QeszNSut', 'jEXrdyCX');


INSERT INTO FRIEND VALUES ('QeszNSut', 'gGaYRiFo');


INSERT INTO FRIEND VALUES ('QeszNSut', 'lBRureMT');


INSERT INTO FRIEND VALUES ('QeszNSut', 'GXnhZnMZ');

